-- =============================================================================
-- Migration: enable_rls
-- =============================================================================
-- Enables Row-Level Security on every tenant-owned table and installs the
-- helper SQL functions that RLS policies reference.
--
-- This migration is hand-written (not generated by Prisma) because Prisma does
-- not model RLS. It runs AFTER the `init` migration that creates all tables.
-- =============================================================================


-- =============================================================================
-- HELPER FUNCTIONS
-- =============================================================================

CREATE OR REPLACE FUNCTION public.current_user_id()
  RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER
AS $$ SELECT auth.uid(); $$;

CREATE OR REPLACE FUNCTION public.current_school_id()
  RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER
AS $$
  SELECT school_id FROM public.users
  WHERE auth_id = auth.uid() AND deleted_at IS NULL LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.current_user_role()
  RETURNS text LANGUAGE sql STABLE SECURITY DEFINER
AS $$
  SELECT role::text FROM public.users
  WHERE auth_id = auth.uid() AND deleted_at IS NULL LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.guardian_student_ids()
  RETURNS uuid[] LANGUAGE sql STABLE SECURITY DEFINER
AS $$
  SELECT COALESCE(ARRAY(
    SELECT g.student_id FROM public.guardians g
    JOIN public.users u ON u.id = g.user_id
    WHERE u.auth_id = auth.uid() AND u.deleted_at IS NULL
  ), '{}'::uuid[]);
$$;


-- =============================================================================
-- ENABLE RLS
-- =============================================================================

ALTER TABLE public.schools             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teachers            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guardians           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classes             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subject_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.terms               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timetable_slots     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_records  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fee_balances        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs          ENABLE ROW LEVEL SECURITY;


-- =============================================================================
-- SCHOOLS
-- =============================================================================

CREATE POLICY "schools_select_own" ON public.schools FOR SELECT
  USING (id = public.current_school_id());


-- =============================================================================
-- USERS
-- =============================================================================

CREATE POLICY "users_select_same_school" ON public.users FOR SELECT
  USING (school_id = public.current_school_id() AND deleted_at IS NULL);

CREATE POLICY "users_insert_admin_only" ON public.users FOR INSERT
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');

CREATE POLICY "users_update_admin_only" ON public.users FOR UPDATE
  USING (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN')
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');


-- =============================================================================
-- STUDENTS
-- =============================================================================

CREATE POLICY "students_select" ON public.students FOR SELECT
  USING (
    school_id = public.current_school_id() AND (
      public.current_user_role() IN ('ADMIN', 'TEACHER')
      OR (public.current_user_role() = 'STUDENT' AND user_id = (
        SELECT id FROM public.users WHERE auth_id = auth.uid() AND deleted_at IS NULL LIMIT 1
      ))
      OR (public.current_user_role() = 'PARENT' AND id = ANY(public.guardian_student_ids()))
    )
  );

CREATE POLICY "students_insert_admin_only" ON public.students FOR INSERT
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');

CREATE POLICY "students_update_admin_only" ON public.students FOR UPDATE
  USING (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN')
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');


-- =============================================================================
-- TEACHERS
-- =============================================================================

CREATE POLICY "teachers_select_same_school" ON public.teachers FOR SELECT
  USING (school_id = public.current_school_id());

CREATE POLICY "teachers_insert_admin_only" ON public.teachers FOR INSERT
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');

CREATE POLICY "teachers_update_admin_only" ON public.teachers FOR UPDATE
  USING (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN')
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');


-- =============================================================================
-- GUARDIANS
-- =============================================================================

CREATE POLICY "guardians_select_admin" ON public.guardians FOR SELECT
  USING (
    public.current_user_role() = 'ADMIN' AND
    student_id IN (SELECT id FROM public.students WHERE school_id = public.current_school_id())
  );

CREATE POLICY "guardians_select_own_parent" ON public.guardians FOR SELECT
  USING (
    public.current_user_role() = 'PARENT' AND
    user_id = (SELECT id FROM public.users WHERE auth_id = auth.uid() AND deleted_at IS NULL LIMIT 1)
  );

CREATE POLICY "guardians_insert_admin_only" ON public.guardians FOR INSERT
  WITH CHECK (
    public.current_user_role() = 'ADMIN' AND
    student_id IN (SELECT id FROM public.students WHERE school_id = public.current_school_id())
  );

CREATE POLICY "guardians_update_admin_only" ON public.guardians FOR UPDATE
  USING (
    public.current_user_role() = 'ADMIN' AND
    student_id IN (SELECT id FROM public.students WHERE school_id = public.current_school_id())
  )
  WITH CHECK (
    public.current_user_role() = 'ADMIN' AND
    student_id IN (SELECT id FROM public.students WHERE school_id = public.current_school_id())
  );


-- =============================================================================
-- CLASSES
-- =============================================================================

CREATE POLICY "classes_select_same_school" ON public.classes FOR SELECT
  USING (school_id = public.current_school_id());

CREATE POLICY "classes_insert_admin_only" ON public.classes FOR INSERT
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');

CREATE POLICY "classes_update_admin_only" ON public.classes FOR UPDATE
  USING (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN')
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');


-- =============================================================================
-- SUBJECTS
-- =============================================================================

CREATE POLICY "subjects_select_same_school" ON public.subjects FOR SELECT
  USING (school_id = public.current_school_id());

CREATE POLICY "subjects_insert_admin_only" ON public.subjects FOR INSERT
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');

CREATE POLICY "subjects_update_admin_only" ON public.subjects FOR UPDATE
  USING (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN')
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');


-- =============================================================================
-- SUBJECT_ASSIGNMENTS
-- =============================================================================

CREATE POLICY "subject_assignments_select_same_school" ON public.subject_assignments FOR SELECT
  USING (class_id IN (SELECT id FROM public.classes WHERE school_id = public.current_school_id()));

CREATE POLICY "subject_assignments_insert_admin_only" ON public.subject_assignments FOR INSERT
  WITH CHECK (
    public.current_user_role() = 'ADMIN' AND
    class_id IN (SELECT id FROM public.classes WHERE school_id = public.current_school_id())
  );

CREATE POLICY "subject_assignments_update_admin_only" ON public.subject_assignments FOR UPDATE
  USING (
    public.current_user_role() = 'ADMIN' AND
    class_id IN (SELECT id FROM public.classes WHERE school_id = public.current_school_id())
  )
  WITH CHECK (
    public.current_user_role() = 'ADMIN' AND
    class_id IN (SELECT id FROM public.classes WHERE school_id = public.current_school_id())
  );

CREATE POLICY "subject_assignments_delete_admin_only" ON public.subject_assignments FOR DELETE
  USING (
    public.current_user_role() = 'ADMIN' AND
    class_id IN (SELECT id FROM public.classes WHERE school_id = public.current_school_id())
  );


-- =============================================================================
-- TERMS
-- =============================================================================

CREATE POLICY "terms_select_same_school" ON public.terms FOR SELECT
  USING (school_id = public.current_school_id());

CREATE POLICY "terms_insert_admin_only" ON public.terms FOR INSERT
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');

CREATE POLICY "terms_update_admin_only" ON public.terms FOR UPDATE
  USING (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN')
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');


-- =============================================================================
-- TIMETABLE_SLOTS
-- =============================================================================

CREATE POLICY "timetable_slots_select_same_school" ON public.timetable_slots FOR SELECT
  USING (school_id = public.current_school_id());

CREATE POLICY "timetable_slots_insert_admin_only" ON public.timetable_slots FOR INSERT
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');

CREATE POLICY "timetable_slots_update_admin_only" ON public.timetable_slots FOR UPDATE
  USING (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN')
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');

CREATE POLICY "timetable_slots_delete_admin_only" ON public.timetable_slots FOR DELETE
  USING (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');


-- =============================================================================
-- ATTENDANCE_RECORDS
-- =============================================================================

CREATE POLICY "attendance_records_select" ON public.attendance_records FOR SELECT
  USING (
    school_id = public.current_school_id() AND (
      public.current_user_role() = 'ADMIN'
      OR (public.current_user_role() = 'TEACHER' AND class_id IN (
        SELECT sa.class_id FROM public.subject_assignments sa
        JOIN public.teachers t ON t.id = sa.teacher_id
        JOIN public.users u ON u.id = t.user_id
        WHERE u.auth_id = auth.uid() AND u.deleted_at IS NULL
      ))
      OR (public.current_user_role() = 'STUDENT' AND student_id = (
        SELECT s.id FROM public.students s
        JOIN public.users u ON u.id = s.user_id
        WHERE u.auth_id = auth.uid() AND u.deleted_at IS NULL LIMIT 1
      ))
      OR (public.current_user_role() = 'PARENT' AND student_id = ANY(public.guardian_student_ids()))
    )
  );

CREATE POLICY "attendance_records_insert_teacher_or_admin" ON public.attendance_records FOR INSERT
  WITH CHECK (
    school_id = public.current_school_id() AND (
      public.current_user_role() = 'ADMIN'
      OR (public.current_user_role() = 'TEACHER' AND class_id IN (
        SELECT sa.class_id FROM public.subject_assignments sa
        JOIN public.teachers t ON t.id = sa.teacher_id
        JOIN public.users u ON u.id = t.user_id
        WHERE u.auth_id = auth.uid() AND u.deleted_at IS NULL
      ))
    )
  );

CREATE POLICY "attendance_records_update_teacher_or_admin" ON public.attendance_records FOR UPDATE
  USING (
    school_id = public.current_school_id() AND (
      public.current_user_role() = 'ADMIN'
      OR (public.current_user_role() = 'TEACHER' AND class_id IN (
        SELECT sa.class_id FROM public.subject_assignments sa
        JOIN public.teachers t ON t.id = sa.teacher_id
        JOIN public.users u ON u.id = t.user_id
        WHERE u.auth_id = auth.uid() AND u.deleted_at IS NULL
      ))
    )
  )
  WITH CHECK (
    school_id = public.current_school_id() AND (
      public.current_user_role() = 'ADMIN'
      OR (public.current_user_role() = 'TEACHER' AND class_id IN (
        SELECT sa.class_id FROM public.subject_assignments sa
        JOIN public.teachers t ON t.id = sa.teacher_id
        JOIN public.users u ON u.id = t.user_id
        WHERE u.auth_id = auth.uid() AND u.deleted_at IS NULL
      ))
    )
  );


-- =============================================================================
-- FEE_BALANCES
-- =============================================================================

CREATE POLICY "fee_balances_select" ON public.fee_balances FOR SELECT
  USING (
    school_id = public.current_school_id() AND (
      public.current_user_role() = 'ADMIN'
      OR (public.current_user_role() = 'PARENT' AND student_id = ANY(public.guardian_student_ids()))
      OR (public.current_user_role() = 'STUDENT' AND student_id = (
        SELECT s.id FROM public.students s
        JOIN public.users u ON u.id = s.user_id
        WHERE u.auth_id = auth.uid() AND u.deleted_at IS NULL LIMIT 1
      ))
    )
  );

CREATE POLICY "fee_balances_insert_admin_only" ON public.fee_balances FOR INSERT
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');

CREATE POLICY "fee_balances_update_admin_only" ON public.fee_balances FOR UPDATE
  USING (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN')
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');


-- =============================================================================
-- ANNOUNCEMENTS
-- =============================================================================

CREATE POLICY "announcements_select" ON public.announcements FOR SELECT
  USING (
    school_id = public.current_school_id() AND (
      audience = 'SCHOOL_WIDE'
      OR public.current_user_role() = 'ADMIN'
      OR (audience = 'GRADE' AND target_grade_level IN (
        SELECT c.grade_level FROM public.classes c
        JOIN public.students s ON s.current_class_id = c.id
        JOIN public.users u ON u.id = s.user_id
        WHERE u.auth_id = auth.uid() AND u.deleted_at IS NULL
        UNION
        SELECT c.grade_level FROM public.classes c
        JOIN public.students s ON s.current_class_id = c.id
        WHERE s.id = ANY(public.guardian_student_ids())
        UNION
        SELECT DISTINCT c.grade_level FROM public.timetable_slots ts
        JOIN public.classes c ON c.id = ts.class_id
        JOIN public.teachers t ON t.id = ts.teacher_id
        JOIN public.users u ON u.id = t.user_id
        WHERE u.auth_id = auth.uid() AND u.deleted_at IS NULL
      ))
      OR (audience = 'CLASS' AND target_class_id IN (
        SELECT s.current_class_id FROM public.students s
        JOIN public.users u ON u.id = s.user_id
        WHERE u.auth_id = auth.uid() AND u.deleted_at IS NULL
        UNION
        SELECT current_class_id FROM public.students
        WHERE id = ANY(public.guardian_student_ids())
        UNION
        SELECT DISTINCT class_id FROM public.timetable_slots ts
        JOIN public.teachers t ON t.id = ts.teacher_id
        JOIN public.users u ON u.id = t.user_id
        WHERE u.auth_id = auth.uid() AND u.deleted_at IS NULL
      ))
    )
  );

CREATE POLICY "announcements_insert_admin_only" ON public.announcements FOR INSERT
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');

CREATE POLICY "announcements_update_admin_only" ON public.announcements FOR UPDATE
  USING (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN')
  WITH CHECK (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');

CREATE POLICY "announcements_delete_admin_only" ON public.announcements FOR DELETE
  USING (school_id = public.current_school_id() AND public.current_user_role() = 'ADMIN');


-- =============================================================================
-- AUDIT_LOGS  (append-only — no UPDATE/DELETE policies)
-- =============================================================================

CREATE POLICY "audit_logs_select_admin" ON public.audit_logs FOR SELECT
  USING (public.current_user_role() = 'ADMIN' AND school_id = public.current_school_id());

CREATE POLICY "audit_logs_select_own" ON public.audit_logs FOR SELECT
  USING (user_id = (
    SELECT id FROM public.users WHERE auth_id = auth.uid() AND deleted_at IS NULL LIMIT 1
  ));

CREATE POLICY "audit_logs_insert_own_school" ON public.audit_logs FOR INSERT
  WITH CHECK (school_id = public.current_school_id() OR school_id IS NULL);
