// =============================================================================
// Dummy PDF generation for seeded `documents` Storage content — reuses
// ReceiptPdfService's exact pdfkit streaming pattern (already an apps/api
// dependency; zero new dependencies needed). Option A from the audit's §8.
// =============================================================================

import PDFDocument from 'pdfkit';

export async function generateSamplePdf(title: string, bodyText: string): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const chunks: Buffer[] = [];
  doc.on('data', (chunk) => chunks.push(chunk));
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });

  doc.fontSize(16).text(title, { align: 'center' });
  doc.moveDown();
  doc.fontSize(11).text(bodyText);
  doc.moveDown();
  doc.fontSize(9).fillColor('#888888').text('This is placeholder content generated by the sample-school seed script — not a real document.');
  doc.end();

  return done;
}

export function sanitizeFilename(name: string): string {
  return name.replace(/[^a-zA-Z0-9._-]/g, '_').slice(-150);
}
