// =============================================================================
// Documents (+ Storage PDFs), conversations, messages, notifications.
// =============================================================================

import { randomUUID } from 'crypto';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { SeedLogger } from './seed-logger';
import { batchInsert } from './db-utils';
import { generateSamplePdf, sanitizeFilename } from './sample-pdfs';
import type { SeededClass, SeededSubject, SeededTeacher, SeededParent } from './types';
import type { Rng } from './kenyan-names';

// -----------------------------------------------------------------------------
// Documents — 4 SCHOOL_WIDE + 4 CLASS + 4 SUBJECT + 18 ASSIGNMENT = 30
// -----------------------------------------------------------------------------

interface DocPlan { title: string; scopeType: 'SCHOOL_WIDE' | 'CLASS' | 'SUBJECT' | 'ASSIGNMENT'; scopeSubtype: 'HOMEWORK' | 'QUIZ' | null; scopeId: string | null; }

export async function seedDocuments(
  admin: SupabaseClient,
  logger: SeedLogger,
  schoolId: string,
  schoolName: string,
  uploadedByUserId: string,
  classes: SeededClass[],
  subjects: SeededSubject[],
  homeworkIds: string[],
  quizIds: string[],
): Promise<void> {
  const plans: DocPlan[] = [
    { title: 'School Handbook', scopeType: 'SCHOOL_WIDE', scopeSubtype: null, scopeId: null },
    { title: 'Term 2 Holiday Schedule', scopeType: 'SCHOOL_WIDE', scopeSubtype: null, scopeId: null },
    { title: 'School Dress Code', scopeType: 'SCHOOL_WIDE', scopeSubtype: null, scopeId: null },
    { title: 'School Calendar', scopeType: 'SCHOOL_WIDE', scopeSubtype: null, scopeId: null },
  ];
  for (const cls of classes.slice(0, 4)) plans.push({ title: `${cls.name} Class Notice`, scopeType: 'CLASS', scopeSubtype: null, scopeId: cls.id });
  for (const subj of subjects.slice(0, 4)) plans.push({ title: `${subj.name} Curriculum Overview`, scopeType: 'SUBJECT', scopeSubtype: null, scopeId: subj.id });
  for (const homeworkId of homeworkIds.slice(0, 12)) plans.push({ title: 'Homework Reference Material', scopeType: 'ASSIGNMENT', scopeSubtype: 'HOMEWORK', scopeId: homeworkId });
  for (const quizId of quizIds.slice(0, 6)) plans.push({ title: 'Quiz Study Guide', scopeType: 'ASSIGNMENT', scopeSubtype: 'QUIZ', scopeId: quizId });

  const rows: Array<{ id: string; school_id: string; uploaded_by_id: string; title: string; file_name: string; file_size: number; mime_type: string; scope_type: string; scope_subtype: string | null; scope_id: string | null; storage_path: string }> = [];

  for (const plan of plans) {
    const buffer = await generateSamplePdf(plan.title, `This is a sample document for ${schoolName} — placeholder content generated by the seed script.`);
    const fileName = `${sanitizeFilename(plan.title)}.pdf`;
    const storagePath = `${schoolId}/${randomUUID()}-${fileName}`;
    const { error: uploadErr } = await admin.storage.from('documents').upload(storagePath, buffer, { contentType: 'application/pdf', upsert: false });
    if (uploadErr) throw new Error(`Storage upload failed for ${plan.title}: ${uploadErr.message}`);

    rows.push({
      id: randomUUID(), school_id: schoolId, uploaded_by_id: uploadedByUserId, title: plan.title, file_name: fileName,
      file_size: buffer.length, mime_type: 'application/pdf', scope_type: plan.scopeType, scope_subtype: plan.scopeSubtype,
      scope_id: plan.scopeId, storage_path: storagePath,
    });
  }

  await batchInsert(admin, logger, 'documents', schoolId, rows);
}

// -----------------------------------------------------------------------------
// Conversations + messages — 3 valid party shapes only (parent<->teacher,
// admin<->teacher, admin<->parent). A STUDENT party is rejected by the
// conversations_reject_student trigger regardless of caller/role — never
// attempted here.
// -----------------------------------------------------------------------------

const SAMPLE_MESSAGE_BODIES = [
  'Good afternoon, just checking in on progress this term.',
  'Thank you for the update, much appreciated.',
  'Could we schedule a short call this week?',
  'Noted, will follow up by Friday.',
  'Please find the details below.',
  'Thanks for letting me know.',
];

export async function seedMessaging(
  admin: SupabaseClient,
  logger: SeedLogger,
  schoolId: string,
  adminUserId: string,
  classTeachers: SeededTeacher[],
  parents: SeededParent[],
  rng: Rng,
): Promise<void> {
  const conversationRows: Array<{ id: string; school_id: string; parent_user_id: string | null; teacher_user_id: string | null; admin_user_id: string | null; student_id: string | null; last_message_body: string; last_message_at: string }> = [];
  const messageRows: Array<{ id: string; school_id: string; conversation_id: string; sender_id: string; body: string; created_at: string }> = [];

  function addConversation(partyA: string, partyB: string, shape: 'parent-teacher' | 'admin-teacher' | 'admin-parent', studentId: string | null): void {
    const id = randomUUID();
    const lastBody = SAMPLE_MESSAGE_BODIES[Math.floor(rng() * SAMPLE_MESSAGE_BODIES.length)]!;
    conversationRows.push({
      id, school_id: schoolId,
      parent_user_id: shape === 'parent-teacher' ? partyA : shape === 'admin-parent' ? partyB : null,
      teacher_user_id: shape === 'parent-teacher' ? partyB : shape === 'admin-teacher' ? partyB : null,
      admin_user_id: shape === 'admin-teacher' ? partyA : shape === 'admin-parent' ? partyA : null,
      student_id: studentId, last_message_body: lastBody, last_message_at: '2026-06-10T12:00:00Z',
    });
    const messageCount = 5 + Math.floor(rng() * 3);
    for (let i = 0; i < messageCount; i++) {
      const sender = i % 2 === 0 ? partyA : partyB;
      messageRows.push({
        id: randomUUID(), school_id: schoolId, conversation_id: id, sender_id: sender,
        body: SAMPLE_MESSAGE_BODIES[Math.floor(rng() * SAMPLE_MESSAGE_BODIES.length)]!,
        created_at: `2026-06-${String(1 + (i % 28)).padStart(2, '0')}T${String(8 + (i % 8)).padStart(2, '0')}:00:00Z`,
      });
    }
  }

  const parentsWithChildren = parents.filter((p) => p.studentIds.length > 0);
  for (let i = 0; i < 5 && i < parentsWithChildren.length && i < classTeachers.length; i++) {
    const parent = parentsWithChildren[i]!;
    const teacher = classTeachers[i]!;
    addConversation(parent.userId, teacher.userId, 'parent-teacher', parent.studentIds[0] ?? null);
  }
  for (let i = 0; i < 5 && i < classTeachers.length; i++) {
    addConversation(adminUserId, classTeachers[i]!.userId, 'admin-teacher', null);
  }
  for (let i = 5; i < 10 && i < parentsWithChildren.length; i++) {
    addConversation(adminUserId, parentsWithChildren[i]!.userId, 'admin-parent', null);
  }

  await batchInsert(admin, logger, 'conversations', schoolId, conversationRows);
  await batchInsert(admin, logger, 'messages', schoolId, messageRows);
}

// -----------------------------------------------------------------------------
// Notifications — minimal, illustrative. Every row gets sms_status:
// 'ABANDONED' (never 'PENDING') — the only code path anywhere in this repo
// that reads notifications.sms_status (NotificationsService.dispatch(),
// which the live-deployed API's @Cron(EVERY_MINUTE) scheduler runs
// continuously) strictly filters `sms_status='PENDING'` at three
// independent points. An ABANDONED row is structurally guaranteed never to
// be picked up, regardless of phone number or Africa's Talking credentials.
// -----------------------------------------------------------------------------

export async function seedNotifications(
  admin: SupabaseClient,
  logger: SeedLogger,
  schoolId: string,
  parents: SeededParent[],
  classTeachers: SeededTeacher[],
  rng: Rng,
): Promise<void> {
  const rows: Array<{ id: string; school_id: string; recipient_id: string; type: string; title: string; body: string; is_read: boolean; sms_status: string; created_at: string }> = [];

  const notifTypes: Array<{ type: string; title: string; body: string }> = [
    { type: 'HOMEWORK_ASSIGNED', title: 'New homework assigned', body: 'A new homework assignment has been posted.' },
    { type: 'NEW_ANNOUNCEMENT', title: 'New school announcement', body: 'Check the announcements board for the latest update.' },
    { type: 'PAYMENT_RECEIVED', title: 'Payment received', body: 'A fee payment has been recorded on your account.' },
    { type: 'ABSENT_STUDENT', title: 'Attendance update', body: 'Your child was marked absent today.' },
  ];

  const recipients = [...parents.filter((p) => p.studentIds.length > 0), ...classTeachers.map((t) => ({ userId: t.userId }))];
  for (let i = 0; i < 40; i++) {
    const recipient = recipients[Math.floor(rng() * recipients.length)];
    if (!recipient) continue;
    const n = notifTypes[Math.floor(rng() * notifTypes.length)]!;
    rows.push({
      id: randomUUID(), school_id: schoolId, recipient_id: recipient.userId, type: n.type, title: n.title, body: n.body,
      is_read: rng() < 0.5, sms_status: 'ABANDONED', created_at: '2026-06-15T10:00:00Z',
    });
  }

  await batchInsert(admin, logger, 'notifications', schoolId, rows);
}
